version: "3.9"
services:
  chatgse:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - flask-app
    networks:
      - biochat
    environment:
      - BASE_URL=http://flask-app:5000

  flask-app:
    build:
      context: ./biochatter-server/
      dockerfile: Dockerfile
    env_file:
      - .bioserver.env
    ports:
      - 5000:5000
    networks:
      - biochat
    volumes:
      - ./logs:/app/logs

networks:
  biochat:
