version: '3.9'
services:
  chatgse:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - flask-app

  flask-app:
    image: frankfeng78/bioserver:v1
    ports:
      - 8000:8000
